/*
  Oracle script for storing AG Grid layout preferences.

  Frontend endpoint mapping:
    GET    /api/grid-layouts/{layoutKey}
    PUT    /api/grid-layouts/{layoutKey}/active
    PUT    /api/grid-layouts/{layoutKey}/layouts/{layoutName}
    DELETE /api/grid-layouts/{layoutKey}/layouts/{layoutName}

  Notes:
    - layout_state_json stores the AG Grid state exactly as sent by the UI.
    - Single Name stores both grids in the same JSON value:
        { "grids": { "single-name-drilldown": {...}, "single-name-lender": {...} } }
    - The active layout is stored on the row with is_active = 1.
    - Oracle unique indexes allow multiple null values, so the function-based
      active index enforces only one active layout per user + page.
*/

CREATE TABLE grid_layout_preference (
    grid_layout_preference_id NUMBER(19, 0)
        GENERATED BY DEFAULT ON NULL AS IDENTITY
        NOT NULL,
    user_id VARCHAR2(128 CHAR) NOT NULL,
    layout_key VARCHAR2(128 CHAR) NOT NULL,
    layout_name VARCHAR2(128 CHAR) NOT NULL,
    layout_state_json CLOB NOT NULL,
    is_active NUMBER(1, 0) DEFAULT 0 NOT NULL,
    created_at_utc TIMESTAMP(3) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    updated_at_utc TIMESTAMP(3) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,

    CONSTRAINT pk_grid_layout_preference
        PRIMARY KEY (grid_layout_preference_id),
    CONSTRAINT uq_grid_layout_pref_user_key_name
        UNIQUE (user_id, layout_key, layout_name),
    CONSTRAINT ck_grid_layout_pref_user_id
        CHECK (LENGTH(TRIM(user_id)) > 0),
    CONSTRAINT ck_grid_layout_pref_layout_key
        CHECK (LENGTH(TRIM(layout_key)) > 0),
    CONSTRAINT ck_grid_layout_pref_layout_name
        CHECK (LENGTH(TRIM(layout_name)) > 0),
    CONSTRAINT ck_grid_layout_pref_name_default
        CHECK (LOWER(TRIM(layout_name)) <> 'default'),
    CONSTRAINT ck_grid_layout_pref_is_active
        CHECK (is_active IN (0, 1)),
    CONSTRAINT ck_grid_layout_pref_state_json
        CHECK (layout_state_json IS JSON)
);

CREATE UNIQUE INDEX ux_grid_layout_pref_active
    ON grid_layout_preference (
        CASE WHEN is_active = 1 THEN user_id END,
        CASE WHEN is_active = 1 THEN layout_key END
    );

CREATE INDEX ix_grid_layout_pref_user_key
    ON grid_layout_preference (user_id, layout_key);

CREATE OR REPLACE TRIGGER trg_grid_layout_pref_updated_at
BEFORE UPDATE ON grid_layout_preference
FOR EACH ROW
BEGIN
    :NEW.updated_at_utc := SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/
